export const linksP=[
    {
        id:1,
        title:"Home",
        url:"/PatientPage"
    },
    {
        id:2,
        title:"Services",
        url:"#services"
    },
    {
        id:3,
        title:"About",
        url:"/About"
    },
    {
        id:4,
        title:"Contact",
        url:"/Contact"
    },
    {
        id:5,
        title:"Login",
        url:"/Login"
    }
    ]